on:
    push:
      branches:
        - main
        - develop
    pull_request:
      types:
        - opened
        - reopened
        - synchronize
        - labeled
name: Default Pipeline
jobs:
  build:
    strategy:
      matrix:
        java-version: [ '11', '17', '21' ]
        os: [ 'ubuntu-latest', 'macos-latest']
        maven-version: [ '3.8.8', '3.9.9', '4.0.0-rc-3' ]
        exclude:
          # 4.0.0 requires java 17+
          - java-version: '11'
            maven-version: '4.0.0-rc-3'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Maven with Java ${{ matrix.java-version }}
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: ${{ matrix.java-version }}
          java-distribution: 'temurin'
          maven-version: ${{ matrix.maven-version }}
      - name: Build with Maven
        run: mvn clean test install
      - name: Build Demo with Maven
        run: |
          cd demo/
          mvn clean test
          

