on:
    push:
      branches:
        - main
        - develop
name: Default Pipeline
jobs:
  build:
    strategy:
      matrix:
        java-version: [ '8', '11', '17', '21' ]
        os: [ 'ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Setup Java ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64
      - name: Build with Maven
        run: mvn clean test

